[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lazydin"
version = "4.2.11"
description = "Lazydin automation tool"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "Lazydin Team"}
]
dependencies = [
    "aiofiles>=24.1.0",
    "aiosqlite>=0.21.0",
    "alembic>=1.16.2",
    "fake-useragent>=2.2.0",
    "fastapi[standard]>=0.115.14",
    "jinja2>=3.1.6",
    "nodriver>=0.47.0",
    "pathlib>=1.0.1",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.41",
    "undetected-chromedriver>=3.5.5",
    "uvicorn>=0.35.0",
]

[project.scripts]
lazydin = "lazydin.__main__:main"

[tool.setuptools]
packages = ["lazydin", "workflows"]

[tool.uv.workspace]
members = ["venv"]

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
]
